# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "posts"
name = "Posts"
url = "/post"

[[main]]
identifier = "awards"
name = "Trophy Room"
url = "/awards"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/spencerja"

[social.params]
icon = "brand-github2"

[[social]]
identifier = "hackthebox"
name = "HackTheBox"
url = "https://app.hackthebox.com/profile/1202496"

[social.params]
icon = "brand-hackthebox2"

[[social]]
identifier = "tryhackme"
name = "TryHackMe"
url = "https://tryhackme.com/p/spencerj"

[social.params]
icon = "brand-tryhackme"

[[social]]
identifier = "ctftime"
name = "Team"
url = "https://ctftime.org/team/217710"

[social.params]
icon = "brand-ctftime"
